version: '3'

networks:
  shell-network:
    driver: bridge

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.2
    container_name: elasticsearch
    networks:
     - shell-network
    ports:
    - "9200:9200"
    - "9300:9300"
    volumes:
    - /tmp:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:8.4.2
    container_name: kibana
    networks:
     - shell-network
    ports:
     - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
     - elasticsearch

  cerebro:
    image: lmenezes/cerebro
    container_name: cerebro
    networks:
     - shell-network
    ports:
     - "9000:9000"

  filebeat:
    image: elastic/filebeat:8.4.2
    volumes:
      - ./ufw.log:/var/log/ufw.log
      - ./logs/imedx1.server.log:/var/log/imedx1.server.log
      - ./logs/imedx2.server.log:/var/log/imedx2.server.log
      - ./logs/imedx3.server.log:/var/log/imedx3.server.log
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
     - shell-network
    depends_on:
     - elasticsearch
    logging:
      driver: elasticsearch
      options:
        hosts: http://elasticsearch:9200

  logstash:
    image: logstash:8.10.2
    container_name: logstash-secshell
    restart: always
    volumes:
      - ./config-dir:/config-dir
      - ./logs:/logs
    depends_on:
      - elasticsearch
    command: logstash -f /config-dir/logstash.conf
    networks:
     - shell-network
    ports:
    - "6000:5000"