version: '3'

networks:
  shell-network:
    driver: bridge

services:

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.10.2"
    container_name: elasticsearch
    networks:
     - shell-network
    ports:
    - "9200:9200"
    - "9300:9300"
    volumes:
    - /tmp:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node


  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    container_name: kibana
    networks:
     - shell-network
    ports:
     - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
     - elasticsearch

  cerebro:
    image: lmenezes/cerebro
    container_name: cerebro
    networks:
     - shell-network
    ports:
     - "9000:9000"

  metricbeat:
    image: elastic/metricbeat:7.10.2
    networks:
     - shell-network
    depends_on:
     - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    volumes:
      - ./ufw.log:/usr/share/metricbeat/data/ufw.log
      - ./logs/imedx1.server.log:/usr/share/metricbeat/data/imedx1.server.log
      - ./logs/imedx2.server.log:/usr/share/metricbeat/data/imedx2.server.log
      - ./logs/imedx3.server.log:/usr/share/metricbeat/data/imedx3.server.log

  filebeat:
    image: elastic/filebeat:7.10.2
    networks:
     - shell-network
    depends_on:
     - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      
    volumes:
      - ./ufw.log:/var/log/ufw.log
      - ./logs/imedx1.server.log:/var/log/imedx1.server.log
      - ./logs/imedx2.server.log:/var/log/imedx2.server.log
      - ./logs/imedx3.server.log:/var/log/imedx3.server.log
        
  logstash:
    image: elastic/logstash:7.10.2
    container_name: logstash-secshell
    restart: always
    volumes:
      - ./config-dir:/config-dir
      - ./logs:/logs
    depends_on:
      - elasticsearch
    command: logstash -f /config-dir/logstash.conf
    networks:
     - shell-network

    

